env:
  browser: true
  es2021: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
  - prettier
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - prettier
rules:
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-explicit-any': off
  ban-types: off
  class-methods-use-this: error
  consistent-return: error
  curly: error
  default-case-last: error
  default-case: error
  dot-notation: error
  eqeqeq: error
  no-await-in-loop: error
  no-delete-var: error
  no-empty-function: error
  no-empty: error
  no-invalid-this: error
  no-multi-spaces: error
  no-new: error
  no-param-reassign: error
  no-shadow: error
  no-undefined: error
  no-unreachable: error
  no-unused-vars: error
  no-use-before-define: error
  no-var: error
  semi: off
  space-before-function-paren: off
