name: CI/CD

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - package.json
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - package.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: npm install
      - name: Build Package
        run: npm run build
      - name: Test Code
        run: npm test
      - uses: codecov/codecov-action@v1
      - name: Publish Package
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Get NPM Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Github Release
        uses: kbrashears5/github-action-release-maker@main
        with:
          VERSION: ${{ steps.package-version.outputs.current-version}}
          TOKEN: ${{ secrets.ACTIONS }}
